### ISSUE TITLE
No response due to getresponse() got an unexpected keyword argument 'buffering

### ISSUE THREAD

**Issue by nevosial** [obsrvbl/flowlogs-reader#36]
The flow_logs_reader hangs while trying to retrieve large result dataset.

`
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
`

**Comment by bbayles** [comment]
Is this the full traceback? Could you post the section of your code that is getting this?

**Comment by nevosial** [comment]
Using the CLI 
$ flowlogs_reader "my-LogGroup" findip <my_ip>

`
^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/flowlogs_reader", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flowlogs_reader/__main__.py", line 235, in main
    action_method(reader, *args.action[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flowlogs_reader/__main__.py", line 69, in action_findip
    for record in reader:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flowlogs_reader/flowlogs_reader.py", line 193, in __next__
    return next(self.iterator)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flowlogs_reader/flowlogs_reader.py", line 202, in _reader
    for event in self._read_streams():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flowlogs_reader/flowlogs_reader.py", line 248, in _read_streams
    for page in response_iterator:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/client.py", line 611, in _make_api_call
    operation_model, request_dict)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/endpoint.py", line 147, in _send_request
    request, operation_model, attempts)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/endpoint.py", line 179, in _get_response
    http_response = self._send(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/endpoint.py", line 223, in _send
    return self.http_session.send(request)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/httpsession.py", line 272, in send
    http_response.content
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/botocore/awsrequest.py", line 587, in content
    self._content = bytes().join(self.raw.stream()) or bytes()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/response.py", line 494, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/response.py", line 442, in read
    data = self._fp.read(amt)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
KeyboardInterrupt`

**Comment by bbayles** [comment]
Did the original exception occur after you pressed Ctrl+C? I expect that this is the actual cause of the error message shown.

Also, can you try using the `--start-time` filter to limit the results?

**Comment by nevosial** [comment]
I ran the example using the python library.
`
`start = datetime.datetime(2018,12,3,21,10,0)
`end = datetime.datetime(2018,12,3,21,30,0)
`flow_logs_reader = FlowLogsReader(log_group_name="myLogGroup",boto_client_kwargs=my_map, `start_time=start, end_time=end)
`print(len(list(flow_logs_reader)))
`

I get the same error after waiting for more than 15 mins and then stopping the execution in pycharm.(have attached the full error log)

[error_log.txt](https://github.com/obsrvbl/flowlogs-reader/files/2650406/error_log.txt)

**Comment by bbayles** [comment]
Thanks for the details.

What about a really short time window - like one minute. Can you get results to come back from that?

**Comment by nevosial** [comment]
Thanks. I did try it for 1 and 2 minute intervals; i get the same error.

`start = datetime.datetime(2018,12,3,21,11,0)
end = datetime.datetime(2018,12,3,21,12,0)
`

**Comment by bbayles** [comment]
Let's take this library out of the loop.

Install the AWS CLI: `pip install awscli`

Make the same query with it:

```
$ aws --region="some-region" logs filter-log-events --log-group-name="some-group" --start-time="1544040000" --end-time="1544040060"
```

How long does that take?

**Comment by bbayles** [comment]
OK, that's interesting. Could you tell me what versions of `botocore` and `boto3` you are using? You can see that this library is using [the very same API calls](https://github.com/obsrvbl/flowlogs-reader/blob/af6cbd796f8ea849a98ca691a2de82c4b696c3cf/flowlogs_reader/flowlogs_reader.py#L238-L245).

**Comment by nevosial** [comment]
Yes i see that but I'm not sure if i'm missing something here, 

boto3 - 1.9.59
botocore - 1.12.59

`
from flowlogs_reader import FlowLogsReader
import datetime, time
import boto3

client = boto3.client('logs')
my_map = {'aws_access_key_id':'mykey','aws_secret_access_key':'myaccess', 'region_name':'my-region-1'}
start = datetime.datetime(2018,12,3,21,10,0)
end = datetime.datetime(2018,12,3,21,11,0)

flow_logs_reader = FlowLogsReader(log_group_name="myLogGroup", boto_client_kwargs=my_map, start_time=start, end_time=end, boto_client=client)
print(list(flow_logs_reader))
`

**Comment by bbayles** [comment]
Hmm, could you delete the `client = boto3.client('logs')` bit? As you can see [here](https://github.com/obsrvbl/flowlogs-reader/blob/af6cbd796f8ea849a98ca691a2de82c4b696c3cf/flowlogs_reader/flowlogs_reader.py#L152-L157), `boto_client_kwargs` are not read if a client is supplied. So your key and such aren't being read.

**Comment by bbayles** [comment]
Also: when you're pasting in code snippets, please use \`\`\` instead of \` to make sure the lines are rendered properly.

**Comment by nevosial** [comment]
Yes, Thank you. removing the client variable doesn't help. i see the **same** error.
I tried updating my 
```my_map = {'service_name':'logs', 'aws_access_key_id':'mykey','aws_secret_access_key':'myaccess', 'region_name':'my-region-1'}```

this update doesn't help as well.

**Comment by bbayles** [comment]
Let's take this library out of the loop again:

Can you run something like this?

```python
import boto3

session = boto3.Session(
    aws_access_key_id='...',
    aws_secret_access_key='...',
    aws_session_token='...',
)
client = session.client('logs', region_name='...')
resp = client.filter_log_events(logGroupName='...'):
print(len(resp['events']))
```

My suspicion is that your `boto3` client isn't actually being initialized with the right information.

**Comment by bbayles** [comment]
There must be an answer here. The library uses the `get_paginator` instead of calling `filter_log_events` directly ([here](https://github.com/obsrvbl/flowlogs-reader/blob/af6cbd796f8ea849a98ca691a2de82c4b696c3cf/flowlogs_reader/flowlogs_reader.py#L238-L245)).

So the next test would be to do:

```python
paginator = client.get_paginator('filter_log_events')
response_iterator = paginator.paginate(
    logGroupName='my_group',
    interleaved=True,
)
for page in response_iterator:
    for event in page['events']:
        print(event)
        assert False
```

If that doesn't work, try leaving the `interleaved` bit out?

**Comment by nevosial** [comment]
The ```get_paginator``` approach (above) works too with and without the ```interleaved``` bit !

**Comment by bbayles** [comment]
We're missing something, I'm sure.

Start with the client that is working manually. Now do:

```python
# Ensure the standard client is working
standard_flow = client.filter_log_events(logGroupName='flowlog_group')['events'][0]
print(standard_flow)

# Attach the standard client to the library and retrieve a flow
reader = FlowLogsReader('flowlog_group')
reader.boto_client = client 
library_flow = next(iter(reader)).to_dict()
print(library_flow)
```

This attaches the working boto client to the reader. Then the reader does [exactly what we just did](https://github.com/obsrvbl/flowlogs-reader/blob/af6cbd796f8ea849a98ca691a2de82c4b696c3cf/flowlogs_reader/flowlogs_reader.py#L238).

What's that give?

**Comment by nevosial** [comment]
The above snippet also works and provides the output. I added the start_time and end_time filter to the above reader; which works fine as well.

**Comment by bbayles** [comment]
Well that's a relief.

This should do the same thing:

```python
# Ensure the standard client is working
standard_flow = client.filter_log_events(logGroupName='flowlog_group')['events'][0]
print(standard_flow)

# Attach the standard client to the library and retrieve a flow
reader = FlowLogsReader('flowlog_group', boto_client=client)
library_flow = next(iter(reader)).to_dict()
print(library_flow)
```

Does it? If not, could you do `print(id(client))` and `print(id(reader.boto_client))`?

**Comment by nevosial** [comment]
Actually, this is what i tried previously along with the start_time and  end_time. This works and I see that the client id in both cases are the same.

**Comment by nevosial** [comment]
The CLI tool without ```findip``` param works fine.

Not sure if i understand right, the library doesn't work as expected. The following code still doesn't work (here i'm setting the session explicitly),

```
import boto3

session = boto3.Session(
    aws_access_key_id='...',
    aws_secret_access_key='...',
    aws_session_token='...',
)
client = session.client('logs', region_name='my-region-1')
start = datetime.datetime(2018,12,3,21,10,0)
end = datetime.datetime(2018,12,3,21,11,0)
flow_logs_reader = FlowLogsReader(log_group_name, boto_client=client, start_time=start, end_time=end)
print(len(list(flow_logs_reader)))
```

The error is the same as seen in the error_log.txt
